create table usuario (
  user_id uuid not null,
  
  nome text not null,
  sobre_nome text not null,
  foto_usuario text,
  tipo text not null,
  email text not null,
  telefone text not null,
  saldo_inicial numeric(15, 2) not null,
  
  constraint usuario_pkey primary key (user_id),
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint usuario_user_id_fkey foreign KEY (user_id) references auth.users (id)
);

create table categorias (
  id bigint primary key generated always as identity,
  nome text not null,
  descricao text not null,
  
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null
);

create table transacoes (
  id bigint generated by default as identity not null,
  data date not null,
  descricao text null,
  valor numeric(15, 2) not null,
  tipo text not null,
  status text not null,
  categoria_id bigint null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  user_id uuid null,
  constraint transacoes_pkey primary key (id),
  constraint transacoes_categoria_id_fkey foreign KEY (categoria_id) references categorias (id),
  constraint transacoes_user_id_fkey foreign KEY (user_id) references auth.users (id),
  constraint transacoes_status_check check (
    (
      status = any (
        array['Aguardando'::text, 'Pago'::text, 'Vencida'::text]
      )
    )
  ),
  constraint transacoes_tipo_check check (
    (
      tipo = any (array['Entrada'::text, 'Saída'::text])
    )
  )
) TABLESPACE pg_default;

-- pedido 1

preciso de uma view com nome de view_valores

precisa retornar o total de 
entradas
saidas
saldo = ( entradas - saidas )

com filtro por usuário.

CREATE VIEW view_valores AS
SELECT 
  user_id,
  SUM(CASE WHEN tipo = 'Entrada' THEN valor ELSE 0 END) AS total_entradas,
  SUM(CASE WHEN tipo = 'Saída' THEN valor ELSE 0 END) AS total_saidas,
  SUM(CASE WHEN tipo = 'Entrada' THEN valor ELSE 0 END) - SUM(CASE WHEN tipo = 'Saída' THEN valor ELSE 0 END) AS saldo
FROM transacoes
GROUP BY user_id;

-- pedido 2
preciso de uma view, que retorne lançamentos diários, 
data, valor, tipo
isso filtrando por user_id

nome view_grafico1

create view view_grafico1 as
select
  data,
  valor,
  tipo
from
  transacoes
where
  user_id is not null;

-- view 3
create view view_grafico2 as
select
  data,
  case
    when tipo = 'Entrada' then 'Entrada'
    else 'Saída'
  end as entrada,
  valor,
  user_id
from
  transacoes
where
  user_id is not null;

insert into
  transacoes (
    data,
    descricao,
    valor,
    tipo,
    status,
    categoria_id,
    user_id
  )
values
  (
    '2023-10-01',
    'Transação 1',
    100.00,
    'Entrada',
    'Pago',
    1,
    '04f797f0-1c27-402f-9312-25d034a770ec'
  ),
  (
    '2023-10-02',
    'Transação 2',
    150.00,
    'Entrada',
    'Pago',
    1,
    '04f797f0-1c27-402f-9312-25d034a770ec'
  ),
  (
    '2023-10-03',
    'Transação 3',
    200.00,
    'Entrada',
    'Pago',
    1,
    '04f797f0-1c27-402f-9312-25d034a770ec'
  ),
  (
    '2023-10-04',
    'Transação 4',
    250.00,
    'Entrada',
    'Pago',
    1,
    '04f797f0-1c27-402f-9312-25d034a770ec'
  ),
  (
    '2023-10-05',
    'Transação 5',
    300.00,
    'Entrada',
    'Pago',
    1,
    '04f797f0-1c27-402f-9312-25d034a770ec'
  ),
  (
    '2023-10-06',
    'Transação 6',
    350.00,
    'Entrada',
    'Pago',
    1,
    '04f797f0-1c27-402f-9312-25d034a770ec'
  ),
  (
    '2023-10-07',
    'Transação 7',
    400.00,
    'Entrada',
    'Pago',
    1,
    '04f797f0-1c27-402f-9312-25d034a770ec'
  ),
  (
    '2023-10-08',
    'Transação 8',
    450.00,
    'Entrada',
    'Pago',
    1,
    '04f797f0-1c27-402f-9312-25d034a770ec'
  ),
  (
    '2023-10-09',
    'Transação 9',
    500.00,
    'Entrada',
    'Pago',
    1,
    '04f797f0-1c27-402f-9312-25d034a770ec'
  ),
  (
    '2023-10-10',
    'Transação 10',
    550.00,
    'Entrada',
    'Pago',
    1,
    '04f797f0-1c27-402f-9312-25d034a770ec'
  );